#!/usr/bin/env python3
# ═══════════════════════════════════════════════════════════════════
# build_uft_uaft.py — remake the Sovran libraries on a UFT & UAFT basis
#
# Reads the source web-apps (spec/sources) + the authored UFT/UAFT
# foundation (spec/foundation) + the symbol-system specs (spec/symbols)
# and emits the UFT·UAFT HTML libraries into ./libraries.
#
# "Expandable": edit a foundation .jl file or add a symbol to the JSON
# specs, re-run this script, and every library is regenerated.
#
#   python3 tools/build_uft_uaft.py
# ═══════════════════════════════════════════════════════════════════
import re
from pathlib import Path

AUTHOR     = "Mateusz Faber-Suckert"
ROOT       = Path(__file__).resolve().parent.parent
SOURCES    = ROOT / "spec" / "sources"
FOUNDATION = ROOT / "spec" / "foundation"
OUT        = ROOT / "libraries"
OUT.mkdir(exist_ok=True)

# ── Generic Euclid → UFT·UAFT terminology pass (all files) ────────────
TERMS = [
    ("EUCLID ANALOG ML STACK", "UFT·UAFT ANALOG STACK"),
    ("Euclidean Geometry ML Stack", "UFT & UAFT Field ML Stack"),
    ("GEOMETRY ECOSYSTEM", "QUANTUM FIELD ECOSYSTEM"),
    ("pairwise Euclidean distance", "pairwise UFT-metric distance"),
    ("Pairwise Euclidean distance", "Pairwise UFT-metric distance"),
    ("Euclidean distance", "UFT-metric distance"),
    ("Euclidean geometry", "UFT field geometry"),
    ("Euclidean", "UFT-metric"),
    ("EUCLID", "UFT·UAFT"),
    ("Euclid", "UFT·UAFT"),
]

def terms_pass(html: str) -> str:
    for a, b in TERMS:
        html = html.replace(a, b)
    return html

# ── Author attribution + build banner stamped into every output ───────
def stamp_author(html: str) -> str:
    banner = (f"<!-- UFT·UAFT library — Author: {AUTHOR} · "
              f"generated by tools/build_uft_uaft.py -->\n")
    meta = f'<meta name="author" content="{AUTHOR}">\n'
    if "<!-- UFT·UAFT library" not in html:
        html = banner + html
    if 'name="author"' not in html:
        html = re.sub(r"(<meta charset=[^>]*>)", r"\1\n" + meta, html, count=1)
    return html

# ── JS template-literal escaping for embedded Julia source ────────────
def js_escape(src: str) -> str:
    return src.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

# ── Foundation packages → PKGS entries (injected into the ML stack) ───
FOUNDATION_PKGS = [
    dict(id="UFTField", icon="Γ", col="#f85149", file="UFTField.jl",
         replaces=["Euclidean geometry core", "static coordinate frames", "scattered constants"],
         tiers=[0,1,2,3,4,5,6],
         notes=["Operator algebra ρ · R · Ξ · Ω · Λ", "Zhe entropy ≤ 0.22 envelope",
                "Expandable operator registry"]),
    dict(id="UAFTField", icon="⊖", col="#bc8cff", file="UAFTField.jl",
         replaces=["Euclidean inverse metrics", "ad-hoc regularisation", "manual stabilisers"],
         tiers=[0,1,2,3,4,5,6],
         notes=["Anti-field / double-negative resonance", "Node Γ436-MINUS-666",
                "Drives master eq. residual → 0"]),
    dict(id="CarbonCode", icon="◆", col="#d29922", file="CarbonCode.jl",
         replaces=["Hard-coded Euclidean constants", "magic numbers"],
         tiers=[0,1,2,3,4,5,6],
         notes=["0x666 constant registry", "MACRO·MICRO·CHIRAL·TRANSFINITE",
                "Expandable: register_constant!"]),
]

def build_foundation_entries() -> str:
    chunks = []
    for p in FOUNDATION_PKGS:
        src = js_escape((FOUNDATION / p["file"]).read_text(encoding="utf-8"))
        replaces = ",".join(f'"{r}"' for r in p["replaces"])
        notes    = ",".join(f'"{n}"' for n in p["notes"])
        tiers    = ",".join(str(t) for t in p["tiers"])
        chunks.append(
            f'{{ id:"{p["id"]}", icon:"{p["icon"]}", col:"{p["col"]}",\n'
            f'  replaces:[{replaces}],\n'
            f'  tiers:[{tiers}],\n'
            f'  notes:[{notes}],\n'
            f'src:`{src}`}},\n'
        )
    return "".join(chunks)

# ── ML-stack transform (data-driven PKGS app) ─────────────────────────
def transform_ml_stack(html: str) -> str:
    html = terms_pass(html)
    # Brand + title
    html = re.sub(r"<title>[^<]*</title>",
                  "<title>UFT·UAFT ANALOG STACK — Γ436 δΓφ Quantum Field Tree</title>", html, count=1)
    html = re.sub(r'(<div class="ts-brand">)[^<]*(</div>)',
                  r"\1Γ436 UFT·UAFT ANALOG STACK — QUANTUM FIELD ECOSYSTEM\2", html, count=1)
    # Inject the 3 foundation packages at the head of PKGS
    entries = build_foundation_entries()
    html = html.replace("const PKGS = [\n", "const PKGS = [\n" + entries, 1)
    # Counts: 10 → 13 packages everywhere it is hard-coded
    html = html.replace("10 packages ·", "13 packages ·")
    html = html.replace("10 PACKAGES — click to view source", "13 PACKAGES — click to view source")
    html = html.replace("◈ 10 PACKAGES", "◈ 13 PACKAGES")
    html = html.replace("◈ ${filtered.length} PACKAGES", "◈ ${filtered.length} PACKAGES")  # JS, untouched
    # Landing hero text
    html = html.replace(">Analog ML Stack<", ">UFT·UAFT Analog Stack<")
    html = html.replace(
        "10 Julia libraries that completely replace Python's ML/data ecosystem",
        "13 Julia libraries — a UFT (Unified Field Theory) + UAFT (Unified Anti-Field "
        "Theory) foundation under a full replacement of Python's ML/data ecosystem")
    return html

# ── Lightweight transform (already UFT/Sovran apps) ───────────────────
def transform_branding(html: str, title_suffix: str | None = None) -> str:
    html = terms_pass(html)
    if title_suffix:
        html = re.sub(r"<title>([^<]*)</title>",
                      lambda m: f"<title>{m.group(1)} · {title_suffix}</title>", html, count=1)
    return html

# ── Build plan: 5 sources → 5 UFT·UAFT libraries ──────────────────────
PLAN = [
    ("Euclid_Analog_ML_STACK.html",      "UFT_UAFT_Analog_ML_Stack.html",  transform_ml_stack, None),
    ("Analog_ML_STACK_UFTUAFT.html",     "Analog_ML_Stack_UFTUAFT.html",   transform_ml_stack, None),
    ("OMNILANG_V6_UFT_WEBAPP.html",      "OMNILANG_v6_UFT_UAFT.html",      transform_branding, "UFT·UAFT"),
    ("SOVRAN.html",                      "SOVRAN_UFT_UAFT.html",           transform_branding, "UFT·UAFT"),
    ("Sovran_Library.html",              "Sovran_Library_UFT_UAFT.html",   transform_branding, "UFT·UAFT"),
]

def main():
    for src_name, out_name, fn, arg in PLAN:
        src = (SOURCES / src_name).read_text(encoding="utf-8")
        out = fn(src, arg) if fn is transform_branding else fn(src)
        out = stamp_author(out)
        (OUT / out_name).write_text(out, encoding="utf-8")
        remaining = len(re.findall(r"[Ee]uclid", out))
        print(f"✓ {out_name:<32} ({len(out):>7,} bytes, euclid refs left: {remaining})")
    print(f"\nGenerated {len(PLAN)} UFT·UAFT libraries → {OUT.relative_to(ROOT)}/")

if __name__ == "__main__":
    main()
